# Generated by Django 4.2.3 on 2023-08-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'کد تایید', 'verbose_name_plural': 'کدهای تایید'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
    ]
