# Generated by Django 4.2.3 on 2023-08-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_author_category_printyear_publisher_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover_type', models.CharField(max_length=50)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('weight', models.SmallIntegerField()),
                ('international_code', models.CharField(max_length=13)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.book')),
            ],
        ),
    ]
