# Generated by Django 4.2.3 on 2023-08-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-created_at',)},
        ),
    ]
