# Generated by Django 4.2.3 on 2023-08-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_book_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryBook',
        ),
    ]
