# Generated by Django 4.2.3 on 2023-08-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='information',
            name='book_cover_type',
            field=models.CharField(max_length=50, verbose_name='نوع جلد کتاب'),
        ),
        migrations.AlterField(
            model_name='information',
            name='international_code',
            field=models.CharField(max_length=13, verbose_name='کد شابک'),
        ),
        migrations.AlterField(
            model_name='information',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد صفحات کتاب'),
        ),
        migrations.AlterField(
            model_name='information',
            name='weight',
            field=models.SmallIntegerField(verbose_name='وزن کتاب'),
        ),
    ]
