# Generated by Django 4.2.3 on 2023-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_information_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discounted_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
