# Generated by Django 4.2.3 on 2023-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_book_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discounted_price',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف خورده'),
        ),
    ]
