# Generated by Django 4.2.3 on 2023-09-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_book_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
    ]
