# Generated by Django 4.2.3 on 2023-07-22 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
