# Generated by Django 4.2.3 on 2023-08-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-pub_date',), 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'لایک', 'verbose_name_plural': 'لایک ها'},
        ),
    ]
