# Generated by Django 4.2.3 on 2023-09-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_comment_body_alter_comment_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
