# Generated by Django 4.2.3 on 2023-10-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_categorycourse_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycourse',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='categorycourse',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
    ]
