# Generated by Django 4.2.3 on 2023-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_categorycourse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
