# Generated by Django 4.2.3 on 2023-08-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='article_comment',
            options={'verbose_name': 'کامنت مقاله', 'verbose_name_plural': 'کامنت های مقاله'},
        ),
        migrations.AlterModelOptions(
            name='articlelike',
            options={'verbose_name': 'لایک مقاله', 'verbose_name_plural': 'لایک های مقاله'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
