# Generated by Django 4.2.3 on 2023-10-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_cat',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
