# Generated by Django 4.2.3 on 2023-10-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_slug_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_cat',
            new_name='slug',
        ),
    ]
