# Generated by Django 4.2.3 on 2023-08-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم مربوط به سفارش', 'verbose_name_plural': 'آیتم های مربوط به سفارشات'},
        ),
    ]
