# Generated by Django 4.2.3 on 2023-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('telegram', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('tiwtter', models.CharField(max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
