# Generated by Django 4.2.3 on 2023-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='footer',
            name='linkedin',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='footer',
            name='tiwtter',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='footer',
            name='whatsapp',
            field=models.CharField(max_length=60),
        ),
    ]
