# Generated by Django 4.2.3 on 2023-08-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_alter_footer_instagram_alter_footer_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='tiwtter',
            new_name='twitter',
        ),
    ]
