# Generated by Django 4.2.3 on 2023-08-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_rename_tiwtter_footer_twitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'پاورقی', 'verbose_name_plural': 'پاورقی ها'},
        ),
    ]
