# Generated by Django 4.2.3 on 2023-08-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_alter_footer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.CharField(max_length=60, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='linkedin',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram',
            field=models.CharField(max_length=60, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter',
            field=models.CharField(max_length=60, verbose_name='توییتر'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='whatsapp',
            field=models.CharField(max_length=60, verbose_name='واتس آپ'),
        ),
    ]
