# Generated by Django 4.2.3 on 2023-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_alter_footer_address_alter_footer_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
